name: Python pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup python
        uses: actions/setup-python@v5
        with:
         python-version: '3.12' 

      - name: Run test
        run:  python firstpythonpipeline.py
